version: '3'

services:

    impala-kudu:
        container_name: impala-kudu
        image: josemyd/all-in-one-impala-kudu
        networks:
            - nifinet

    nifi-database:
        container_name: nifi_oracle_db
        image: 'gvenzl/oracle-xe:18-slim'
        restart: always
        ports:
            - '1521:1521'
        cpus : 1
        mem_limit: 2G
        mem_reservation: 1G
        environment:
            - ORACLE_PASSWORD='admin'
        healthcheck:
            test: [ "CMD", "healthcheck.sh" ]
            interval: "60s"
            timeout: "3s"
            start_period: "15s"
            retries: 5
        command: ls
        volumes:
            - ./scripts:/container-entrypoint-initdb.d
            - oracle-data:/opt/oracle/oradata
        networks:
            - nifinet

    nifi-registry:
        container_name: nifi_registry_container
        image: 'apache/nifi-registry:1.15.0'
        ports:
            - "18080:18080"
        cpus: 1
        mem_limit: 500M
        mem_reservation: 200M
        healthcheck:
            test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:18080/nifi-registry/}"
            interval: "60s"
            timeout: "3s"
            start_period: "5s"
            retries: 5
        networks:
            - nifinet

    nifi-client:
        container_name: nifi_container
        image: 'apache/nifi:1.14.0'
        restart: on-failure
        ports:
            - '8443:8080'
        cpus : 1
        mem_limit: 2G
        mem_reservation: 1G
        environment:
            - NIFI_WEB_HTTP_PORT=8080
            - SINGLE_USER_CREDENTIALS_USERNAME=admin
            - SINGLE_USER_CREDENTIALS_PASSWORD=admin0000000
            - NIFI_SENSITIVE_PROPS_KEY='12345678901234567890A'
        healthcheck:
            test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:8443/nifi/}"
            interval: "60s"
            timeout: "3s"
            start_period: "5s"
            retries: 5
        volumes:
            - nifi_content_repository:/opt/nifi/nifi-current/content_repository
            - nifi_database_repository:/opt/nifi/nifi-current/database_repository
            - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
            - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
            - nifi_state:/opt/nifi/nifi-current/state
            - nifi_logs:/opt/nifi/nifi-current/logs
            - nifi_data:/opt/nifi/nifi-current/data
            - nifi_conf:/opt/nifi/nifi-current/conf
            - type: bind
              source: ./drivers
              target: /opt/nifi/nifi-current/drivers
        depends_on:
            nifi-database:
                condition: service_healthy
        networks:
            - nifinet

volumes:
    oracle-data:
        driver: local
    nifi_content_repository:
        driver: local
    nifi_database_repository:
        driver: local
    nifi_flowfile_repository:
        driver: local
    nifi_provenance_repository:
        driver: local
    nifi_state:
        driver: local
    nifi_logs:
        driver: local
    nifi_data:
        driver: local
    nifi_conf:
        driver: local

networks:
  nifinet:
    driver: bridge